import { MigrationInterface, QueryRunner } from 'typeorm'

import { Pet } from '#/shared/entities/Pet'

export class PopulatePetsTable1742586592681 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const petData = [
      {
        lk_pet_code: 'P-21-03-2025-0001',
        name: 'Luna',
        breed: 'Labrador Retriever',
        specie: 'Dog',
        is_available: true,
        is_house_trained: true,
        health: 'Excellent health, vaccinated',
      },
      {
        lk_pet_code: 'P-21-03-2025-0002',
        name: 'Max',
        breed: 'German Shepherd',
        specie: 'Dog',
        is_available: true,
        is_house_trained: true,
        health: 'Good health, minor hip dysplasia',
      },
      {
        lk_pet_code: 'P-21-03-2025-0003',
        name: 'Bella',
        breed: 'Golden Retriever',
        specie: 'Dog',
        is_available: true,
        is_house_trained: true,
        health: 'Excellent health, all vaccinations up to date',
      },
      {
        lk_pet_code: 'P-21-03-2025-0004',
        name: 'Cooper',
        breed: 'Beagle',
        specie: 'Dog',
        is_available: false,
        is_house_trained: true,
        health: 'Good health, recovering from minor surgery',
      },
      {
        lk_pet_code: 'P-21-03-2025-0005',
        name: 'Daisy',
        breed: 'French Bulldog',
        specie: 'Dog',
        is_available: true,
        is_house_trained: false,
        health: 'Excellent health, needs allergy medication',
      },
      {
        lk_pet_code: 'P-21-03-2025-0006',
        name: 'Rocky',
        breed: 'Boxer',
        specie: 'Dog',
        is_available: true,
        is_house_trained: true,
        health: 'Good health, slight heart murmur',
      },
      {
        lk_pet_code: 'P-21-03-2025-0007',
        name: 'Charlie',
        breed: 'Siberian Husky',
        specie: 'Dog',
        is_available: false,
        is_house_trained: true,
        health: 'Excellent health, active and energetic',
      },
      {
        lk_pet_code: 'P-21-03-2025-0008',
        name: 'Lucy',
        breed: 'Dachshund',
        specie: 'Dog',
        is_available: true,
        is_house_trained: false,
        health: 'Good health, needs dental cleaning',
      },
      {
        lk_pet_code: 'P-21-03-2025-0009',
        name: 'Milo',
        breed: 'Poodle',
        specie: 'Dog',
        is_available: true,
        is_house_trained: true,
        health: 'Excellent health, hypoallergenic',
      },
      {
        lk_pet_code: 'P-21-03-2025-0010',
        name: 'Bailey',
        breed: 'Shih Tzu',
        specie: 'Dog',
        is_available: false,
        is_house_trained: true,
        health: 'Good health, mild skin condition',
      },
      {
        lk_pet_code: 'P-21-03-2025-0011',
        name: 'Teddy',
        breed: 'Maine Coon',
        specie: 'Cat',
        is_available: true,
        is_house_trained: true,
        health: 'Excellent health, recently neutered',
      },
      {
        lk_pet_code: 'P-21-03-2025-0012',
        name: 'Lola',
        breed: 'Siamese',
        specie: 'Cat',
        is_available: true,
        is_house_trained: true,
        health: 'Good health, slight vision impairment',
      },
      {
        lk_pet_code: 'P-21-03-2025-0013',
        name: 'Oscar',
        breed: 'Ragdoll',
        specie: 'Cat',
        is_available: false,
        is_house_trained: true,
        health: 'Excellent health, very docile',
      },
      {
        lk_pet_code: 'P-21-03-2025-0014',
        name: 'Zoe',
        breed: 'Bengal',
        specie: 'Cat',
        is_available: true,
        is_house_trained: false,
        health: 'Good health, high energy level',
      },
      {
        lk_pet_code: 'P-21-03-2025-0015',
        name: 'Leo',
        breed: 'Persian',
        specie: 'Cat',
        is_available: true,
        is_house_trained: true,
        health: 'Good health, requires regular grooming',
      },
      {
        lk_pet_code: 'P-21-03-2025-0016',
        name: 'Lily',
        breed: 'Scottish Fold',
        specie: 'Cat',
        is_available: false,
        is_house_trained: true,
        health: 'Excellent health, very affectionate',
      },
      {
        lk_pet_code: 'P-21-03-2025-0017',
        name: 'Oliver',
        breed: 'American Shorthair',
        specie: 'Cat',
        is_available: true,
        is_house_trained: true,
        health: 'Good health, up to date on vaccinations',
      },
      {
        lk_pet_code: 'P-21-03-2025-0018',
        name: 'Chloe',
        breed: 'British Shorthair',
        specie: 'Cat',
        is_available: true,
        is_house_trained: false,
        health: 'Excellent health, slightly overweight',
      },
      {
        lk_pet_code: 'P-21-03-2025-0019',
        name: 'Simba',
        breed: 'Abyssinian',
        specie: 'Cat',
        is_available: false,
        is_house_trained: true,
        health: 'Good health, playful and active',
      },
      {
        lk_pet_code: 'P-21-03-2025-0020',
        name: 'Coco',
        breed: 'Sphynx',
        specie: 'Cat',
        is_available: true,
        is_house_trained: true,
        health: 'Excellent health, requires special skin care',
      },
    ]

    await queryRunner.manager.save(Pet, petData)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const petCodes = [
      'P-21-03-2025-0001',
      'P-21-03-2025-0002',
      'P-21-03-2025-0003',
      'P-21-03-2025-0004',
      'P-21-03-2025-0005',
      'P-21-03-2025-0006',
      'P-21-03-2025-0007',
      'P-21-03-2025-0008',
      'P-21-03-2025-0009',
      'P-21-03-2025-0010',
      'P-21-03-2025-0011',
      'P-21-03-2025-0012',
      'P-21-03-2025-0013',
      'P-21-03-2025-0014',
      'P-21-03-2025-0015',
      'P-21-03-2025-0016',
      'P-21-03-2025-0017',
      'P-21-03-2025-0018',
      'P-21-03-2025-0019',
      'P-21-03-2025-0020',
    ]

    await Promise.all(petCodes.map(code => queryRunner.manager.delete(Pet, { lk_pet_code: code })))
  }
}
